FROM alpine

RUN apk update

RUN apk add vsftpd

ARG PORT
ARG FOLDER_PARTAGE

EXPOSE $PORT

# Création du dossier
RUN mkdir -p $FOLDER_PARTAGE
RUN ln -s $FOLDER_PARTAGE /partage

ADD vsftpd.conf /etc/vsftpd/

CMD ["vsftpd", "/etc/vsftpd/vsftpd.conf"]