version: '2.0'

services:
    portainer:
        build: .
        container_name: "Tunnel_Tor"
        ports:
            - "9050:9050"
        networks: 
            network:
                aliases:
                    - tor
networks: 
    network:
        driver: bridge