version: '3'

services:
  squid:
    image: datadog/squid:latest
    container_name: squid
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - <local_storage>:/var/log/squid
      - <local_storage>:/etc/squid/squid.conf
